name: ecommerce_application
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

#-------------PACKAGES--------------#

dependencies:
  flutter:
    sdk: flutter

    #Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #State Management

  get: ^4.6.5
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^5.0.0


flutter:
  
  uses-material-design: true

  #-------------LOCAL ASSETS-------------#
  assets:
    - assets/logos/
    - assets/images/

  #------------FONTS-------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 300
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
